### ISSUE TITLE
Comparison with QCNET on performance

### ISSUE THREAD

**Issue by ZhoubinXM** [opendilab/SmartRefine#5]
![image](https://github.com/opendilab/SmartRefine/assets/44090409/ff9f9349-9c63-4b06-903f-51cfe94ec62e)
I noticed that the indicators of the refine module using in QCNET are consistent with the indicators of the adaptive method. Does this mean that the refine module of qcnet is also effective?

**Comment by youngzhou1999** [comment]
Hi, thanks for your interest in our paper.

The refine module of qcnet is straightforward and effective. It belongs to the one-iteration refinement method.

However. it incorporates a relatively large refinement network (similar to its backbone model seen in [https://github.com/ZikangZhou/QCNet/blob/main/modules/qcnet_decoder.py#L89-L116](https://github.com/ZikangZhou/QCNet/blob/main/modules/qcnet_decoder.py#L89-L116)) that has 2,200K parameters (7x than ours). As presented in Tab.2 of our paper, our refinement module based on qcnet (no ref) achieves consistent performance compared with qcnet while introducing fewer Flops (47.4G vs 55.8G), parameters (5.8M vs 7.7M) and latency (363ms vs 392ms).
